apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkassist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parkassist
  template:
    metadata:
      labels:
        app: parkassist
    spec:
      containers:
        - name: parkassist
          image: 107018319445.dkr.ecr.sa-east-1.amazonaws.com/park-assist:v1
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: parkassist # Service name
spec:
    type: LoadBalancer # Expose the service to the internet
    ports:
        - port: 8080
          targetPort: 8080
    selector:
        app: parkassist # Pod label
