apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: park-assist
  namespace: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: park-assist
  minReplicas: 1
  maxReplicas: 10
  behavior:
      scaleDown:
        stabilizationWindowSeconds: 300 # tempo medio usado para tomada de decisao
        policies:
        - type: Pods
          value: 2
          periodSeconds: 30
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
