---
apiVersion: v1
kind: Namespace
metadata:
  name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: park-assist
  namespace: staging
spec:
  selector:
    matchLabels:
      app: park-assist
  template:
    metadata:
      labels:
        app: park-assist
    spec:
      containers:
        - name: park-assist
#          image: AWS_ACCOUNT_ID.dkr.ecr.AWS_REGION.amazonaws.com/park-assist:GITSHA
          image: 585707473057.dkr.ecr.us-east-1.amazonaws.com/park-assist:82fbfd6b81877856b1e95f930ff276e8e01e508b
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 512Mi