apiVersion: apps/v1
kind: Deployment
metadata:
  name: park-assist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: park-assist
  template:
    metadata:
      labels:
        app: park-assist
    spec:
      containers:
        - name: park-assist
          image: 585707473057.dkr.ecr.us-east-1.amazonaws.com/park-assist:v1
          ports:
            - containerPort: 8080

---
# Load Balancer Service
apiVersion: v1
kind: Service
metadata:
  name: park-assist
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: park-assist